version: '3'
services:

  tomcat-app:
    image: tomcat:latest
    container_name: tomcat-container
    ports:
      - "8082:8080"
    volumes:
      - ./target:/usr/local/tomcat/webapps/
      - ./monsterhunter.db:/usr/local/tomcat/monsterhunter.db
    networks:
      - monsterhunter-network


volumes:
  monsterhunter-volume:
networks:
  monsterhunter-network: