version: '2'
services:

  tomcat-app:
    image: tomcat:latest
    container_name: tomcat-container
    ports:
      - "8082:8080"
    volumes:
      - ./target:/usr/local/tomcat/webapps/
    networks:
      - monstehunter-network


volumes:
  monstehunter-volume:
networks:
  monstehunter-network: